Initial State:  os.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=4096, f_bfree=3045, 
                f_bavail=3045, f_files=128, f_ffree=123, f_favail=123, f_flag=4102, f_namemax=252)
Traceback (most recent call last):
  File "/h/u2/csc369h/fall/pub/tester/a5/test.py", line 28, in run_test
    test_function(submission, log)
  File "/h/u2/csc369h/fall/pub/tester/a5/tests.py", line 762, in test
    s.run(grow, timeout=5)
  File "/h/u2/csc369h/fall/pub/tester/a5/submission.py", line 301, in run
    return self._run(timeout, cwd, fn, *args, **kwargs)
  File "/h/u2/csc369h/fall/pub/tester/a5/submission.py", line 236, in _run
    raise exception_chain(fn_exc, vsfs_exc, timeout_exc)
  File "/h/u2/csc369h/fall/pub/tester/a5/submission.py", line 224, in _run
    return future.result(timeout)
  File "/usr/local/packages/python-3.10/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/packages/python-3.10/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/packages/python-3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/h/u2/csc369h/fall/pub/tester/a5/tests.py", line 739, in grow
    os.truncate(fname, newsize)
OSError: [Errno 38] Function not implemented: 'truncate_me'

